---
####
# Create initial user credentials on jenkins
#
####
- name: access jenkins crumb {{jenkins_url_user}}/{{jenkins_url_password}}
  uri:
      url: 'http://localhost:{{jenkins_port}}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'
      user: "{{jenkins_url_user}}"
      password: "{{jenkins_url_password}}"
      force_basic_auth: yes
      return_content: yes
  register: crumb

- name: create jenkins credential user "{{ jenkins_credential_id }}"/{{jenkins_port}}
  uri:
      url: 'http://localhost:{{jenkins_port}}/credentials/store/system/domain/_/createCredentials'
      method: POST
      user: "{{jenkins_url_user}}"
      password: "{{jenkins_url_password}}"
      force_basic_auth: yes
      status_code: 302,200
      headers:
        Jenkins-Crumb: "{{ crumb.content.split(':')[1] }}"
      body: |
        json={
           "": "0",
           "credentials": {
           "scope": "{{ jenkins_credential_scope }}",
           "id": "{{ jenkins_credential_id }}",
           "username": "{{ jenkins_credential_username }}",
           "password": "{{ jenkins_credential_password }}",
           "description": "{{ jenkins_credential_desc }}",
           "$class": "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"
          }
        }