---
###########################
# creates a temporary directory 
# creates a directory for scripts
# downloads the rpm file into the temporary directory 
###########################
  - name: Creates temporary directory "{{ var_download }}"
    file:
      path: "{{ var_download }}"
      mode: 0775
      force: no
      state: directory
    become_user: "{{ installation_user }}"

  - name: Creates scripts directory "{{ var_download }}/scripts"
    file:
      path: "{{ var_download }}/scripts"
      mode: 0775
      force: no
      state: directory
    become_user: "{{ installation_user }}"

# copy the repo file
  - name: download rpm from repo into temporary location "{{ var_download }}"
    get_url:
      url: "{{ jenkins_rpm_url }}/{{ jenkins_source}}"
      dest: "{{ var_download }}"
      mode: 0644
      force: no
    become_user: "{{ installation_user }}"