---
# /sonar/tasks/createdb.yml
  - name: Create a database for Sonar.
    mysql_db:
      name: "{{ sonar_mysql_database }}"
      login_host: "{{ sonar_mysql_host }}"
      login_user: "{{ sonar_user }}"
      state: present

  - name: Create a sonar user.
    mysql_user:
       name: "{{ sonar_mysql_username }}"
       host: "{{ item }}"
       priv: "{{ sonar_mysql_database }}.*:ALL"
       password: "{{ sonar_mysql_password }}"
    with_items: "{{ sonar_mysql_allowed_hosts }}"
